### ISSUE TITLE
when org data is nil, knife vra barfs

### ISSUE THREAD

**Issue by thenoid** [chef-partners/vmware-vra-gem#27]
@adamleff said to open this! blame him ;)

```
chef> knife vra catalog list -VV
INFO: Using configuration from C:/Users/rolsen/.chef/knife.rb
FATAL: Unknown resource error : undefined method `[]' for nil:NilClass
C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.5.3/lib/vra/catalog_item.rb:75:in `subtenant_name': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:62:in `block in get_resource_col_val'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:61:in `each'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:61:in `get_resource_col_val'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:79:in `block in list'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:77:in `each'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:77:in `list'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:38:in `execute_command'
        from C:/Users/rolsen/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/command.rb:51:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/knife.rb:148:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:59:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:59:in `<main>'
```

**Comment by adamleff** [comment]
Talked with @thenoid in Slack about this. His vRA catalog items are missing organization data for reasons unknown. The gem just return nil for the org-related data rather than raising an exception. I'll put up a PR for that.

**Comment by adamleff** [comment]
v1.5.4 of the vmware-vra gem has been released.
