### ISSUE TITLE
general 500 server errors should generate better error messages

### ISSUE THREAD

**Issue by adamleff** [chef-partners/vmware-vra-gem#3]
```
[aleff@dev01a knife-vrealize]$ bundle exec knife vra catalog list -VV
INFO: Using configuration from /home/aleff/.chef/knife.rb
/home/aleff/vmware-vra-gem/lib/vra/client.rb:184:in `raise_http_exception': 500 Internal Server Error (Vra::Exception::HTTPError)
	from /home/aleff/vmware-vra-gem/lib/vra/client.rb:160:in `rescue in http_post'
	from /home/aleff/vmware-vra-gem/lib/vra/client.rb:152:in `http_post'
	from /home/aleff/vmware-vra-gem/lib/vra/client.rb:92:in `generate_bearer_token'
	from /home/aleff/vmware-vra-gem/lib/vra/client.rb:74:in `authorize!'
```

This was with a bad password and should raise a better error message.

**Comment by adamleff** [comment]
Resolved in #1.
